// Article text is not redistributed (publisher copyright). This module is generated by
// analysis/p20_build_app_sample.py from the source corpus and holds, for each item code,
// {published, outlet, text}, plus each coder's item order.
export const ITEMS = {};
export const ORDER = { C01: [], C02: [], T00: [] };
