"""p02_descriptives.py -- TRB-P Step 2: descriptives, Table 1, Fig 2.

Emits tables/table1.tex (coverage-tier descriptives, per-row heat shading + N
data bars) and figures/fig2.pdf (three-panel corpus attention anatomy). Dumps corpus
descriptives to data_build/results.json.
"""
from __future__ import annotations
import numpy as np
import pandas as pd
import common as C
from common import PED, HIGHLIGHT, SECONDARY, NEUTRAL, INK
import palette

TIERS = ["1", "2-3", "4-9", "10+"]
TIER_LABEL = {"1": "1 article", "2-3": "2--3", "4-9": "4--9", "10+": "$\\ge$10"}


def fmt_pct(x): return f"{100*x:.0f}\\%"
def fmt_med(x): return f"{x:.0f}" if not np.isnan(x) else "--"


def shaded_cell(val_str, t, dark_text_thresh=0.62):
    """Return a \\cellcolor-shaded cell; white text when the fill is dark."""
    hexc = palette.ramp_hex(t).lstrip("#")
    if t >= dark_text_thresh:
        return f"\\cellcolor[HTML]{{{hexc}}}\\textcolor{{white}}{{{val_str}}}"
    return f"\\cellcolor[HTML]{{{hexc}}}{val_str}"


def row_norm(vals):
    """Min-max normalise a row of numeric values to [0,1] for the ramp."""
    v = np.array(vals, dtype=float)
    finite = v[np.isfinite(v)]
    if finite.size == 0:
        return np.zeros_like(v)
    lo, hi = finite.min(), finite.max()
    if hi - lo < 1e-12:
        return np.full_like(v, 0.5)
    out = (v - lo) / (hi - lo)
    out[~np.isfinite(out)] = 0.0
    return out


def build_table1(df: pd.DataFrame) -> dict:
    groups = {t: df[df.cov_tier == t] for t in TIERS}
    groups["All"] = df
    cols = TIERS + ["All"]
    total = len(df)

    # metric rows: (label, func mapping subframe->value, formatter, is_pct)
    def med_age(g):
        a = g.age_youngest.dropna()
        return a.median() if len(a) else np.nan
    rows = [
        ("Events, $n$",              lambda g: len(g),                    "N"),
        ("Median articles",          lambda g: g.n_articles.median(),     "med"),
        ("Median outlets",           lambda g: g.n_outlets.median(),      "med"),
        ("Victim named",             lambda g: g.victim_named.mean(),     "pct"),
        ("Median victim age, yr",    med_age,                             "med"),
        ("Child ($\\le$12)",         lambda g: g.child.mean(),            "pct"),
        ("Age $\\ge$65",             lambda g: g.elderly.mean(),          "pct"),
        ("Female",                   lambda g: g.female.mean(),           "pct"),
        ("Hit-and-run",              lambda g: g.hit_run_flag.mean(),     "pct"),
        ("Charges reported",         lambda g: g.charges_reported.mean(), "pct"),
        ("Dark conditions",          lambda g: g.dark.mean(),             "pct"),
        ("Multi-fatality",           lambda g: g.multi_fatality.mean(),   "pct"),
    ]

    lines = []
    lines.append("% Auto-generated by p02_descriptives.py -- do not edit by hand.")
    lines.append("\\begin{tabular}{l cccc c}")
    lines.append("\\toprule")
    hdr = " & ".join(["Coverage tier"] + [TIER_LABEL[t] for t in TIERS] + ["All"]) + " \\\\"
    lines.append(hdr)
    # subheader: N and % per tier
    subvals = []
    for t in TIERS:
        n = len(groups[t]); subvals.append(f"{n:,}")
    lines.append("\\midrule")

    payload_rows = {}
    for label, func, kind in rows:
        vals = [func(groups[c]) for c in cols]
        payload_rows[label] = {c: (None if (isinstance(v, float) and np.isnan(v)) else float(v))
                               for c, v in zip(cols, vals)}
        if kind == "N":
            # data bars, bar proportion = n / total
            cells = []
            for c in cols:
                n = len(groups[c])
                pct = 100 * n / total
                lab = f"{n:,}" if c != "All" else f"\\textbf{{{n:,}}}"
                cells.append(f"\\databarL{{{n}}}{{{total}}}{{{lab}}}")
            lines.append(f"{label} & " + " & ".join(cells) + " \\\\")
            lines.append("\\addlinespace[1pt]")
            continue
        # heat-shaded numeric cells; normalise across the 4 tier columns only
        tvals = [func(groups[t]) for t in TIERS]
        norms = row_norm(tvals)
        # extend normalisation to All using same lo/hi
        allv = func(groups["All"])
        finite = np.array([v for v in tvals if np.isfinite(v)], float)
        lo, hi = (finite.min(), finite.max()) if finite.size else (0, 1)
        all_t = 0.5 if hi - lo < 1e-12 else np.clip((allv - lo) / (hi - lo), 0, 1)
        fmt = (lambda x: fmt_pct(x)) if kind == "pct" else (lambda x: fmt_med(x))
        cells = []
        for t, tv, nt in zip(TIERS, tvals, norms):
            cells.append(shaded_cell(fmt(tv), nt))
        cells.append(shaded_cell(fmt(allv), float(all_t)))
        lines.append(f"{label} & " + " & ".join(cells) + " \\\\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    (C.TABLES / "table1.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[table1] wrote {C.TABLES/'table1.tex'}")
    return payload_rows


def _fig2_legacy(df: pd.DataFrame):
    plt = C.use_style()
    import matplotlib.ticker as mticker
    fig, axes = plt.subplots(2, 2, figsize=(6.5, 5.4), constrained_layout=True)
    (axa, axb), (axc, axd) = axes

    # ---- (a) monthly events (bars) + articles (line) ----
    m = df.dropna(subset=["event_date"]).copy()
    m["ym"] = m["event_date"].dt.to_period("M").dt.to_timestamp()
    monthly = m.groupby("ym").agg(events=("event_id", "size"),
                                  articles=("n_articles", "sum")).reset_index()
    axa.bar(monthly.ym, monthly.events, width=25, color=PED, alpha=0.85,
            label="Events", linewidth=0)
    axa2 = axa.twinx()
    axa2.plot(monthly.ym, monthly.articles, color=HIGHLIGHT, linewidth=1.1,
              label="Articles")
    axa2.grid(False)
    axa2.spines["top"].set_visible(False)
    axa2.set_ylabel("Articles / month", color=HIGHLIGHT, fontsize=8)
    axa2.tick_params(axis="y", labelcolor=HIGHLIGHT)
    axa.set_ylabel("Events / month", color=PED, fontsize=8)
    axa.tick_params(axis="y", labelcolor=PED)
    # era annotations
    ytop = monthly.events.max()
    for (x0, x1), txt in [((pd.Timestamp("2020-03-01"), pd.Timestamp("2021-06-30")), "2020-21\ndip"),
                          ((pd.Timestamp("2023-01-01"), pd.Timestamp("2023-12-31")), "2023\nexpansion")]:
        axa.axvspan(x0, x1, color=NEUTRAL, alpha=0.12, linewidth=0)
        axa.text(x0 + (x1 - x0) / 2, ytop * 1.02, txt, fontsize=5.6,
                 color=INK, ha="center", va="top")
    axa.set_title("Monthly events and article volume", fontsize=8.5)
    C.panel_label(axa, "a")

    # ---- (b) ranked lollipop of events per state ----
    sc = df.state.value_counts().sort_values(ascending=True)
    sc = sc.tail(26)  # top 26 for legibility (full width)
    y = np.arange(len(sc))
    axb.hlines(y, 0, sc.values, color=NEUTRAL, linewidth=0.8)
    axb.plot(sc.values, y, "o", color=PED, markersize=3.2)
    axb.set_yticks(y)
    axb.set_yticklabels(sc.index, fontsize=5.6)
    axb.set_xlabel("Events, 2016--2025")
    axb.set_title("Events per state (top 26)", fontsize=8.5)
    axb.grid(axis="x")
    axb.grid(axis="y", visible=False)
    C.panel_label(axb, "b")

    # ---- (c) articles-per-event: log-x hist + empirical survival ----
    y_art = df.n_articles.values
    maxa = int(y_art.max())
    bins = np.logspace(0, np.log10(maxa + 1), 30)
    axc.hist(y_art, bins=bins, color=PED, alpha=0.80, linewidth=0)
    axc.set_xscale("log"); axc.set_yscale("log")
    axc.set_xlabel("Articles per event"); axc.set_ylabel("Events (log)")
    axc.set_title("Coverage-intensity distribution", fontsize=8.5)
    # empirical survival overlay P(Y>=y)
    axc2 = axc.twinx()
    xs = np.sort(np.unique(y_art))
    surv = np.array([(y_art >= x).mean() for x in xs])
    axc2.plot(xs, surv, color=HIGHLIGHT, linewidth=1.2)
    axc2.set_yscale("log"); axc2.set_ylabel("P(Y $\\geq$ y)", color=HIGHLIGHT, fontsize=8)
    axc2.tick_params(axis="y", labelcolor=HIGHLIGHT)
    axc2.grid(False); axc2.spines["top"].set_visible(False)
    C.panel_label(axc, "c")

    # ---- (d) attention lifespan: span_days vs n_articles ----
    d = df[(df.n_articles >= 1)].copy()
    span = d.span_days.fillna(0).clip(lower=0).values + 0.5   # +0.5 to show single-day on log
    na = d.n_articles.values.astype(float)
    hb = axd.hexbin(span, na, xscale="log", yscale="log", gridsize=28,
                    cmap=palette.seq_cmap(), mincnt=1, linewidths=0, bins="log")
    axd.set_xlabel("Coverage lifespan (days, first$\\rightarrow$last article)")
    axd.set_ylabel("Articles per event")
    axd.set_title("Attention lifespan vs intensity", fontsize=8.5)
    cb = fig.colorbar(hb, ax=axd, shrink=0.85, pad=0.02)
    cb.set_label("Events (log$_{10}$)", fontsize=7)
    cb.ax.tick_params(labelsize=6)
    C.panel_label(axd, "d")

    fig.savefig(C.FIGURES / "fig2.pdf")
    fig.savefig(C.FIGURES / "fig2.png", dpi=600)
    plt.close(fig)
    print(f"[fig2] wrote {C.FIGURES/'fig2.pdf'}")


TIER_COLORS = ["#BFD7EA", "#82B6D7", "#3F8FC1", PED]
TIER_DISPLAY = {
    "1": "1 article", "2-3": "2-3 articles", "4-9": "4-9 articles", "10+": "≥10 articles",
}
DURATION_LABELS = ["Same day", "1 day", "2-7 days", "8-30 days", ">30 days"]


def _flow_patch(x0, x1, y0, y1, height, color):
    """Create one smooth, area-preserving alluvial ribbon."""
    from matplotlib.path import Path
    from matplotlib.patches import PathPatch

    bend = (x1 - x0) * 0.38
    vertices = [
        (x0, y0),
        (x0 + bend, y0), (x1 - bend, y1), (x1, y1),
        (x1, y1 + height),
        (x1 - bend, y1 + height), (x0 + bend, y0 + height), (x0, y0 + height),
        (x0, y0),
    ]
    codes = [Path.MOVETO, Path.CURVE4, Path.CURVE4, Path.CURVE4,
             Path.LINETO, Path.CURVE4, Path.CURVE4, Path.CURVE4, Path.CLOSEPOLY]
    return PathPatch(Path(vertices, codes), facecolor=color, edgecolor="white",
                     linewidth=0.24, alpha=0.82, zorder=1)


def _attention_pathways(ax, df: pd.DataFrame):
    """Draw the event-preserving flow from intensity tier to persistence tier."""
    from matplotlib.patches import Rectangle

    d = df.copy()
    d["duration_bin"] = pd.cut(
        d.span_days.fillna(0).clip(lower=0),
        bins=[-1, 0, 1, 7, 30, np.inf], labels=DURATION_LABELS,
    )
    flows = pd.crosstab(d.cov_tier, d.duration_bin).reindex(
        index=TIERS, columns=DURATION_LABELS, fill_value=0,
    )
    source_totals = flows.sum(axis=1)
    target_totals = flows.sum(axis=0)
    n_total = int(flows.to_numpy().sum())

    gap = 0.034
    scale = (1 - gap * (len(TIERS) - 1)) / n_total

    def stack_bounds(totals):
        y = 0.0
        bounds = {}
        for key, value in totals.items():
            height = float(value) * scale
            bounds[key] = (y, y + height)
            y += height + gap
        return bounds

    source_bounds = stack_bounds(source_totals)
    target_bounds = stack_bounds(target_totals)
    source_cursor = {key: source_bounds[key][0] for key in TIERS}
    target_cursor = {key: target_bounds[key][0] for key in DURATION_LABELS}

    for tier, color in zip(TIERS, TIER_COLORS):
        for duration in DURATION_LABELS:
            count = int(flows.loc[tier, duration])
            if not count:
                continue
            height = count * scale
            ax.add_patch(_flow_patch(0.14, 0.84, source_cursor[tier],
                                     target_cursor[duration], height, color))
            source_cursor[tier] += height
            target_cursor[duration] += height

    # Source and destination strata make every ribbon width directly auditable.
    for tier, color in zip(TIERS, TIER_COLORS):
        lo, hi = source_bounds[tier]
        ax.add_patch(Rectangle((0.105, lo), 0.035, hi - lo, facecolor=color,
                               edgecolor="white", linewidth=0.7, zorder=2))

    for tier in ["1", "2-3"]:
        lo, hi = source_bounds[tier]
        count = int(source_totals.loc[tier])
        ax.text(0.088, (lo + hi) / 2, f"{TIER_DISPLAY[tier]}\n{count:,} ({count / n_total:.1%})",
                ha="right", va="center", fontsize=6.0, color=INK, linespacing=1.12)

    source_label_y = {"10+": 0.992, "4-9": 0.922}
    for tier, y_text in source_label_y.items():
        lo, hi = source_bounds[tier]
        count = int(source_totals.loc[tier])
        ax.plot([0.105, 0.092], [(lo + hi) / 2, y_text], color="#AEBCC6",
                linewidth=0.45, clip_on=False, zorder=2)
        ax.text(0.087, y_text, f"{TIER_DISPLAY[tier]}: {count:,} ({count / n_total:.1%})",
                ha="right", va="center", fontsize=5.8, color=INK)

    for duration in DURATION_LABELS:
        lo, hi = target_bounds[duration]
        ax.add_patch(Rectangle((0.84, lo), 0.035, hi - lo, facecolor="#E9EFF3",
                               edgecolor="white", linewidth=0.7, zorder=2))

    # The four rare persistence strata are deliberately fanned into a label gutter,
    # avoiding unreadable collisions while retaining one-to-one leader lines.
    label_y = {">30 days": 0.985, "8-30 days": 0.915, "2-7 days": 0.845, "1 day": 0.775}
    for duration, y_text in label_y.items():
        lo, hi = target_bounds[duration]
        count = int(target_totals.loc[duration])
        ax.plot([0.875, 0.91], [(lo + hi) / 2, y_text], color="#AEBCC6",
                linewidth=0.45, clip_on=False, zorder=2)
        ax.text(0.918, y_text, f"{duration}: {count:,} ({count / n_total:.1%})",
                ha="left", va="center", fontsize=5.8, color=INK)

    lo, hi = target_bounds["Same day"]
    count = int(target_totals.loc["Same day"])
    ax.text(0.918, (lo + hi) / 2, f"Same day\n{count:,} ({count / n_total:.1%})",
            ha="left", va="center", fontsize=6.0, color=INK, linespacing=1.12)

    ax.set_xlim(0, 1.25)
    ax.set_ylim(-0.015, 1.075)
    ax.set_axis_off()


def _attention_persistence_matrix(ax, df: pd.DataFrame):
    """Show the conditional lifespan profile associated with each coverage tier."""
    from matplotlib.patches import FancyBboxPatch

    d = df.copy()
    d["duration_bin"] = pd.cut(
        d.span_days.fillna(0).clip(lower=0),
        bins=[-1, 0, 1, 7, 30, np.inf], labels=DURATION_LABELS,
    )
    counts = pd.crosstab(d.cov_tier, d.duration_bin).reindex(
        index=TIERS, columns=DURATION_LABELS, fill_value=0,
    )
    row_total = counts.sum(axis=1)
    conditional = counts.div(row_total, axis=0)
    follow_up = 1 - conditional["Same day"]
    n_total = int(row_total.sum())

    matrix_left, cell_width, cell_gap = 0.285, 0.112, 0.013
    cell_height = 0.142
    y_positions = [0.655, 0.468, 0.281, 0.094]
    follow_x, follow_width = 0.925, 0.205
    cmap = palette.seq_cmap()

    ax.text(matrix_left, 0.902, "Coverage lifespan after first article", ha="left",
            va="bottom", fontsize=6.6, fontweight="bold", color=INK)
    for col, duration in enumerate(DURATION_LABELS):
        x = matrix_left + col * (cell_width + cell_gap)
        ax.text(x + cell_width / 2, 0.853, duration, ha="center", va="bottom",
                fontsize=6.0, fontweight="bold", color=INK)
    ax.text(follow_x + follow_width / 2, 0.853, "Follow-up\n(≥1 day)", ha="center",
            va="bottom", fontsize=6.0, fontweight="bold", color=HIGHLIGHT,
            linespacing=1.0)

    for tier, y in zip(TIERS, y_positions):
        total = int(row_total.loc[tier])
        ax.text(matrix_left - 0.027, y + cell_height / 2,
                f"{TIER_DISPLAY[tier]}\n{total:,} events ({total / n_total:.1%})",
                ha="right", va="center", fontsize=6.0, color=INK, linespacing=1.1)

        for col, duration in enumerate(DURATION_LABELS):
            x = matrix_left + col * (cell_width + cell_gap)
            count = int(counts.loc[tier, duration])
            share = float(conditional.loc[tier, duration])
            shade = 0.04 + 0.96 * np.sqrt(share)
            color = cmap(shade)
            card = FancyBboxPatch(
                (x, y), cell_width, cell_height,
                boxstyle="round,pad=0.004,rounding_size=0.014",
                facecolor=color, edgecolor="white", linewidth=0.8,
            )
            ax.add_patch(card)
            text_color = "white" if share >= 0.54 else INK
            label = f"{count:,}\n{share:.0%}" if count else "0\n0%"
            ax.text(x + cell_width / 2, y + cell_height / 2, label,
                    ha="center", va="center", fontsize=6.0, fontweight="bold",
                    color=text_color, linespacing=1.05)

        follow = float(follow_up.loc[tier])
        track = FancyBboxPatch(
            (follow_x, y), follow_width, cell_height,
            boxstyle="round,pad=0.004,rounding_size=0.014",
            facecolor="#F1F3F4", edgecolor="white", linewidth=0.8,
        )
        ax.add_patch(track)
        if follow > 0:
            fill = FancyBboxPatch(
                (follow_x, y), follow_width * follow, cell_height,
                boxstyle="round,pad=0.004,rounding_size=0.014",
                facecolor=HIGHLIGHT, edgecolor="none", linewidth=0,
            )
            ax.add_patch(fill)
        follow_color = "white" if follow >= 0.43 else INK
        ax.text(follow_x + follow_width / 2, y + cell_height / 2, f"{follow:.0%}",
                ha="center", va="center", fontsize=6.2, fontweight="bold", color=follow_color)

    ax.text(matrix_left, 0.035,
            "Cells show event count and within-tier share; color intensity encodes conditional persistence.",
            ha="left", va="bottom", fontsize=5.6, color=NEUTRAL)
    ax.set_xlim(0, 1.18)
    ax.set_ylim(0, 1.0)
    ax.set_axis_off()


def _attention_phase_space(ax, df: pd.DataFrame):
    """Render a smoothed phase-space density for coverage intensity and lifespan."""
    import matplotlib.ticker as mticker

    span = df.span_days.fillna(0).clip(lower=0).to_numpy(float)
    articles = df.n_articles.to_numpy(float)
    x = np.log1p(span)
    y = np.log10(articles)
    x_edges = np.linspace(0, np.log1p(span.max() + 1), 40)
    y_edges = np.linspace(0, np.log10(articles.max()), 34)
    density, _, _ = np.histogram2d(x, y, bins=(x_edges, y_edges))

    # A small binomial blur creates a smooth density field without adding a new dependency.
    kernel = np.array([1, 4, 6, 4, 1], dtype=float) / 16
    for _ in range(2):
        density = np.apply_along_axis(lambda v: np.convolve(v, kernel, mode="same"), 0, density)
        density = np.apply_along_axis(lambda v: np.convolve(v, kernel, mode="same"), 1, density)
    field = np.log1p(density)
    field /= field.max()
    x_mid = (x_edges[:-1] + x_edges[1:]) / 2
    y_mid = (y_edges[:-1] + y_edges[1:]) / 2

    ax.contourf(x_mid, y_mid, field.T,
                levels=[0.035, 0.08, 0.15, 0.28, 0.45, 0.65, 1.0],
                cmap=palette.seq_cmap(), antialiased=True, zorder=1)
    ax.contour(x_mid, y_mid, field.T, levels=[0.08, 0.20, 0.40, 0.65],
               colors="white", linewidths=0.55, alpha=0.9, zorder=2)

    medians = (df.groupby("cov_tier", observed=True).agg(
        lifespan=("span_days", "median"), articles=("n_articles", "median")
    ).reindex(TIERS))
    ax.plot(np.log1p(medians.lifespan), np.log10(medians.articles), color=INK,
            linewidth=1.0, marker="o", markersize=3.4, zorder=4)
    endpoint = medians.loc["10+"]
    ax.annotate("Tier medians", (np.log1p(endpoint.lifespan), np.log10(endpoint.articles)),
                xytext=(5, 4), textcoords="offset points", fontsize=5.3,
                color=INK, zorder=5)

    # Spearman correlation without requiring SciPy: Pearson correlation of average ranks.
    rho = np.corrcoef(pd.Series(span).rank().to_numpy(),
                      pd.Series(articles).rank().to_numpy())[0, 1]
    single_story = ((span == 0) & (articles == 1)).mean()
    persistent = (span >= 8).mean()
    ax.text(0.98, 0.96, f"Spearman ρ = {rho:.2f}", transform=ax.transAxes,
            ha="right", va="top", fontsize=5.9, color=INK)
    ax.text(0.055, 0.80, f"Same-day, one story\n{single_story:.0%} of events",
            transform=ax.transAxes, ha="left", va="top", fontsize=5.6, color=INK,
            bbox=dict(facecolor="white", edgecolor="none", alpha=0.82, pad=1.1), zorder=5)
    ax.annotate(f"Persistent tail (≥8 days)\n{persistent:.1%} of events",
                xy=(np.log1p(12), np.log10(4)), xytext=(2.7, 1.72), textcoords="data",
                arrowprops=dict(arrowstyle="-", color=INK, linewidth=0.55),
                fontsize=5.5, color=INK, zorder=5)

    day_ticks = np.array([0, 1, 7, 30, 180, 475])
    article_ticks = np.array([1, 2, 5, 10, 50, 226])
    ax.xaxis.set_major_locator(mticker.FixedLocator(np.log1p(day_ticks)))
    ax.xaxis.set_major_formatter(mticker.FixedFormatter([str(v) for v in day_ticks]))
    ax.yaxis.set_major_locator(mticker.FixedLocator(np.log10(article_ticks)))
    ax.yaxis.set_major_formatter(mticker.FixedFormatter([str(v) for v in article_ticks]))
    ax.set_xlim(0, np.log1p(475))
    ax.set_ylim(0, np.log10(226))
    ax.set_xlabel("Coverage lifespan (days)")
    ax.set_ylabel("Articles per event")
    ax.grid(False)


def _persistence_survival(ax, df: pd.DataFrame):
    """Plot event-level persistence survival functions stratified by coverage intensity."""
    import matplotlib.ticker as mticker

    time = np.r_[0, np.arange(1, 31), [45, 60, 90, 180, 365, 475]]
    colors = ["#9DAAB3", "#78B5D8", "#3C8FC1", PED]
    for tier, color in zip(TIERS, colors):
        span = df.loc[df.cov_tier == tier, "span_days"].fillna(0).clip(lower=0).to_numpy(float)
        survival = np.array([(span >= t).mean() for t in time])
        ax.step(time, survival, where="post", color=color, linewidth=1.45,
                label=TIER_DISPLAY[tier], zorder=3)
        ax.scatter([1], [survival[1]], s=10, color=color, edgecolor="white",
                   linewidth=0.35, zorder=4)

    ax.set_xscale("symlog", linthresh=1, linscale=0.85)
    ax.set_xlim(0, 475)
    ax.set_ylim(-0.02, 1.04)
    ax.xaxis.set_major_locator(mticker.FixedLocator([0, 1, 7, 30, 180, 475]))
    ax.xaxis.set_major_formatter(mticker.FixedFormatter(["0", "1", "7", "30", "180", "475"]))
    ax.yaxis.set_major_locator(mticker.FixedLocator([0, 0.25, 0.50, 0.75, 1.0]))
    ax.yaxis.set_major_formatter(mticker.PercentFormatter(1, decimals=0))
    ax.set_xlabel("Days since first article")
    ax.set_ylabel("Events still receiving attention")
    ax.legend(title="Coverage tier", title_fontsize=6.0, fontsize=5.8,
              loc="upper right", handlelength=1.5, labelspacing=0.35)
    ax.text(0.02, 0.06, "Markers: probability of follow-up after day 1", transform=ax.transAxes,
            ha="left", va="bottom", fontsize=5.4, color=NEUTRAL)


def _panel_title(ax, letter: str, title: str):
    """Add a left-anchored panel heading with a fixed title-to-axes offset."""
    heading = ax.set_title(f"({letter})  {title}", loc="left", pad=10)
    heading.set_x(0)
    heading.set_ha("left")
    return heading


def fig2(df: pd.DataFrame):
    """Compose a data-driven, three-panel anatomy of observed news attention."""
    plt = C.use_style()
    import matplotlib.dates as mdates
    import matplotlib.ticker as mticker

    fig = plt.figure(figsize=(7.15, 6.15), constrained_layout=True, facecolor="white")
    # A direct shared GridSpec, rather than a nested top-left grid, locks the
    # rendered widths of Panels A and C to the same column geometry.
    grid = fig.add_gridspec(4, 2, height_ratios=[2.1, 1.0, 0.22, 3.15],
                           width_ratios=[1.24, 1.0], wspace=0.08, hspace=0.08)
    axa_volume = fig.add_subplot(grid[0, 0])
    axa_intensity = fig.add_subplot(grid[1, 0], sharex=axa_volume)
    axb = fig.add_subplot(grid[:2, 1])
    axc = fig.add_subplot(grid[3, 0])
    axd = fig.add_subplot(grid[3, 1])

    # (a) Volume and coverage intensity use separate, aligned axes to avoid dual-scale distortion.
    monthly = (df.dropna(subset=["event_date"]).assign(
        ym=lambda x: x.event_date.dt.to_period("M").dt.to_timestamp()
    ).groupby("ym").agg(events=("event_id", "size"), articles=("n_articles", "sum"))
     .reset_index())
    monthly["articles_per_event"] = monthly.articles / monthly.events
    monthly["events_smooth"] = monthly.events.rolling(12, center=True, min_periods=6).mean()
    monthly["intensity_smooth"] = monthly.articles_per_event.rolling(
        12, center=True, min_periods=6
    ).mean()

    axa_volume.bar(monthly.ym, monthly.events, width=24, color="#D3E5F1",
                   edgecolor="none", zorder=1)
    axa_volume.plot(monthly.ym, monthly.events_smooth, color=PED, linewidth=1.55,
                    zorder=3)
    axa_volume.axvspan(pd.Timestamp("2020-03-01"), pd.Timestamp("2021-06-30"),
                       color="#F1F3F4", zorder=0)
    axa_volume.text(pd.Timestamp("2020-10-01"), axa_volume.get_ylim()[1] * 0.95,
                    "2020-2021", ha="center", va="top", fontsize=6.0, color=NEUTRAL)
    axa_volume.set_ylabel("Events per month")
    _panel_title(axa_volume, "a", "Temporal Profile of Observed Coverage")
    axa_volume.tick_params(labelbottom=False)
    axa_volume.set_ylim(bottom=0)

    overall_mean = df.n_articles.mean()
    axa_intensity.plot(monthly.ym, monthly.articles_per_event, color="#C7D3DB",
                        linewidth=0.65, zorder=1)
    axa_intensity.plot(monthly.ym, monthly.intensity_smooth, color=HIGHLIGHT,
                        linewidth=1.45, zorder=3)
    axa_intensity.axhline(overall_mean, color=INK, linewidth=0.65,
                           linestyle=(0, (2, 2)), zorder=2)
    axa_intensity.annotate(f"Overall mean = {overall_mean:.2f}",
                           xy=(monthly.ym.iloc[-2], overall_mean), xytext=(-2, 3),
                           textcoords="offset points", ha="right", va="bottom",
                           fontsize=5.9, color=INK)
    axa_intensity.set_ylabel("Articles per event")
    axa_intensity.set_xlabel("Event date")
    axa_intensity.xaxis.set_major_locator(mdates.YearLocator(2))
    axa_intensity.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    axa_intensity.set_ylim(bottom=max(0, monthly.articles_per_event.min() * 0.78))
    fig.align_ylabels([axa_volume, axa_intensity])
    axa_volume.yaxis.set_label_coords(-0.115, 0.5)
    axa_intensity.yaxis.set_label_coords(-0.115, 0.5)

    # (b) The mirrored composition encodes the difference between events and all linked attention.
    tier = (df.groupby("cov_tier", observed=True).agg(
        events=("event_id", "size"), articles=("n_articles", "sum")
    ).reindex(TIERS))
    tier["event_share"] = tier.events / tier.events.sum()
    tier["article_share"] = tier.articles / tier.articles.sum()
    y = np.arange(len(TIERS))[::-1]
    axb.barh(y, -tier.event_share.to_numpy(), height=0.56, color=PED,
             edgecolor="white", linewidth=0.55, alpha=0.92)
    axb.barh(y, tier.article_share.to_numpy(), height=0.56, color=HIGHLIGHT,
             edgecolor="white", linewidth=0.55, alpha=0.92)
    axb.axvline(0, color=INK, linewidth=0.7, zorder=0)
    for yi, (_, row) in zip(y, tier.iterrows()):
        if row.event_share >= 0.10:
            event_x, event_ha, event_color = -row.event_share / 2, "center", "white"
        else:
            event_x, event_ha, event_color = -row.event_share - 0.022, "right", INK
        if row.article_share >= 0.10:
            article_x, article_ha, article_color = row.article_share / 2, "center", "white"
        else:
            article_x, article_ha, article_color = row.article_share + 0.022, "left", INK
        axb.text(event_x, yi, f"{row.event_share:.1%}", ha=event_ha, va="center",
                 fontsize=6.2, fontweight="bold", color=event_color)
        axb.text(article_x, yi, f"{row.article_share:.1%}", ha=article_ha, va="center",
                 fontsize=6.2, fontweight="bold", color=article_color)
    axb.text(0.25, 0.925, "Share of events", transform=axb.transAxes,
             ha="center", va="bottom", fontsize=7.1, fontweight="bold", color=PED)
    axb.text(0.75, 0.925, "Share of linked articles", transform=axb.transAxes,
             ha="center", va="bottom", fontsize=7.1, fontweight="bold", color=HIGHLIGHT)
    axb.set_yticks(y)
    axb.set_yticklabels([TIER_DISPLAY[t] for t in TIERS])
    axb.set_xlabel("Share of corpus (%)")
    axb.set_ylabel("Coverage tier")
    axb.set_xlim(-0.87, 0.87)
    axb.set_ylim(-0.65, 3.9)
    axb.xaxis.set_major_locator(mticker.FixedLocator([-0.8, -0.4, 0, 0.4, 0.8]))
    axb.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{abs(x) * 100:.0f}"))
    axb.grid(False)
    # Keep the column's y-axis reference line visible so Panels B and D share
    # one exact left-hand visual anchor.
    axb.spines["left"].set_visible(True)
    axb.spines["left"].set_color(INK)
    axb.spines["left"].set_linewidth(0.8)
    axb.spines["bottom"].set_color("#BFC7CC")
    axb.tick_params(axis="y", length=0)
    _panel_title(axb, "b", "Coverage Allocation by Intensity Tier")

    # (c-d) The phase-space field and survival curves make the intensity-persistence relationship explicit.
    _attention_phase_space(axc, df)
    _persistence_survival(axd, df)
    fig.align_ylabels([axb, axd])
    _panel_title(axc, "c", "Attention Phase Space")
    _panel_title(axd, "d", "Persistence Survival by Coverage Intensity")

    fig.savefig(C.FIGURES / "fig2.pdf", facecolor="white")
    fig.savefig(C.FIGURES / "fig2.png", dpi=600, facecolor="white")
    plt.close(fig)
    print(f"[fig2] wrote {C.FIGURES/'fig2.pdf'}")


def main():
    df = C.load_events()
    payload = build_table1(df)
    fig2(df)

    # descriptives to results.json
    desc = {
        "n_events": int(len(df)),
        "n_articles_total": int(df.n_articles.sum()),
        "median_articles": float(df.n_articles.median()),
        "mean_articles": float(df.n_articles.mean()),
        "max_articles": int(df.n_articles.max()),
        "pct_single_article": float((df.n_articles == 1).mean()),
        "median_outlets": float(df.n_outlets.median()),
        "followup_rate": float(df.got_followup.mean()),
        "pct_victim_named": float(df.victim_named.mean()),
        "tier_counts": {t: int((df.cov_tier == t).sum()) for t in TIERS},
        "table1_rows": payload,
        "years": [int(df.year.min()), int(df.year.max())],
        "n_states": int(df.state.nunique()),
    }
    C.update_results("descriptives", desc)
    print("[results] descriptives written")
    print(f"  median articles={desc['median_articles']}, "
          f"single-article share={desc['pct_single_article']:.1%}, "
          f"follow-up rate={desc['followup_rate']:.1%}")


if __name__ == "__main__":
    main()
