"""p14_make_table2.py -- table2.tex from the single specification.

One rule for every covariate: an indicator for "the first linked article
reported X", with no missing-category indicator anywhere. The second column
repeats the identical model with predictors read from the consolidated event
record instead, which is the comparison that exposes outcome-dependent
ascertainment.

Reads data_build/single_spec.json and writes tables/table2.tex.
"""
from __future__ import annotations
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / "tables" / "table2.tex"
LMIN, LMAX = 0.5, 3.0

d = json.load(open(ROOT / "data_build" / "single_spec.json"))
FA_M, EV_M = d["first_article_main"], d["event_level_main"]
FA_S, EV_S = d["first_article_sec"], d["event_level_sec"]


def cell(rr, lo, hi, hollow=False):
    g = "\\ciglyphhollow" if hollow else "\\ciglyph"
    return ("%.2f (%.2f--%.2f) & %s{%.3f}{%.3f}{%.3f}{%s}{%s}"
            % (rr, lo, hi, g, lo, rr, hi, LMIN, LMAX))


def row(lab, k, fa, ev):
    a = cell(fa["rr"][k], fa["ci"][k][0], fa["ci"][k][1])
    b = cell(ev["rr"][k], ev["ci"][k][0], ev["ci"][k][1], hollow=True)
    return "\\quad %s & %s & %s \\\\" % (lab, a, b)


L = ["% Auto-generated by p14_make_table2.py -- do not edit by hand.",
     "\\begin{tabular}{l r@{\\hskip 2pt}c r@{\\hskip 2pt}c}",
     "\\toprule",
     " & \\multicolumn{2}{c}{First-article predictors} & "
     "\\multicolumn{2}{c}{Event-record predictors} \\\\",
     "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
     "Coverage-intensity covariate & RR (95\\% CI) & forest & RR (95\\% CI) & forest \\\\",
     "\\midrule",
     "\\multicolumn{5}{l}{\\emph{Victim attributes}}\\\\"]
for lab, k in [("Child ($\\le$12)", "child"), ("Teen (13--19)", "teen"),
               ("Age $\\ge$65", "elderly"), ("Female victim", "female"),
               ("Victim named", "victim_named")]:
    L.append(row(lab, k, FA_M, EV_M))

L += ["\\addlinespace[2pt]", "\\multicolumn{5}{l}{\\emph{Crash attributes}}\\\\"]
for lab, k in [("Hit-and-run", "hit_run_flag"),
               ("Multi-fatality", "multi_fatality"), ("Weekend", "weekend")]:
    L.append(row(lab, k, FA_M, EV_M))

L += ["\\addlinespace[2pt]",
      "\\multicolumn{5}{l}{\\emph{Context covariates (secondary model)}}\\\\"]
for lab, k in [("Dark conditions", "dark"), ("Charges reported", "charges_reported")]:
    L.append(row(lab, k, FA_S, EV_S))

L += ["\\bottomrule", "\\end{tabular}"]
OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
print("wrote", OUT)
print("\n".join(L))
